<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-02-24 at 23:36:13.
 */
class MD5HasherTest extends \HashDB2\Testing\Hashing_TestCase
{
    /**
     * Sets up the fixture
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
      $this->init(
        new \HashDB2\Hashers\MD5Hasher(),
        "test string",
        "6f8db599de986fab7a21625b7916589c",
        "d41d8cd98f00b204e9800998ecf8427e"
        );
    }

    /**
     * @covers \HashDB2\Hashers\MD5Hasher::__construct
     * @covers \HashDB2\Hashers\Hasher::__construct
     * @covers \HashDB2\Hashers\Hasher::getHashName
     */
    public function testSuccessfulInitializeAndGetHashName()
    {    
      $cn = get_class($this->hasher);
      $parts = explode('\\', $cn);
      $this->assertEquals($parts[count($parts)-1], 'MD5Hasher');
      $this->assertEquals(strtolower($this->hasher->getHashName()), 'md5');
    }
}
